### PR TITLE
Update simplicity

### PR DESCRIPTION
**Pull request by uncomputable**
Bump the MSRV, update rust-simplicity and add some new CI. ~~Add the foundations for enabling codecov for the repo.~~

### CODE REVIEW

**Comment by uncomputable** [comment]
```
Package ‘cargo-llvm-cov-0.6.11’ in /nix/store/1lwg74im5q4fmdk3zf5az570kixzk3vb-source/pkgs/development/tools/rust/cargo-llvm-cov/default.nix:86 is marked as broken, refusing to evaluate.
```
Okay, let's remove cargo-llvm-cov for now.

**Comment by uncomputable** [comment]
Drafted because of https://github.com/BlockstreamResearch/rust-simplicity/pull/250

**Comment by uncomputable** [comment]
Undraft, as https://github.com/BlockstreamResearch/rust-simplicity/pull/250 is merged.

**Review by apoelstra — APPROVED** [review]
ACK d2f77b5989bdc0e7f11b3d6e7aaf08fb1881be07 successfully ran local tests

**Pull request merged**
