### PR TITLE
More functions

### PR DESCRIPTION
**Pull request by uncomputable**
Update jet signatures and add a pseudo namespace. Disable `check_sig_verify`. Introduce the inbuilt functions `assert!`, `panic!` and `is_none`. These changes make Simfony programs look more like Rust.

### CODE REVIEW

**Comment by uncomputable** [comment]
Clippy `--all-targets` seems to work. (Relief)

**Review by apoelstra — APPROVED** [review]
ACK 680cd817dc65c08eb0f0e95e7751a36416ce7d29

**Comment by uncomputable** [comment]
Resolved a rebase conflict

**Comment by uncomputable** [comment]
Made CI pass. We need CI on this crate :)

**Review by apoelstra — APPROVED** [review]
ACK e91f6e342f0d959044fc14e92b7011c5cfcbe5b8

**Pull request merged**
